import { LegalLayout, LegalSection } from "./LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" updated="September 23, 2026">
      <LegalSection title="1. Agreement">
        <p>
          These Terms govern your use of WorkPulse ("the Service") operated by Codenscious ("we", "us").
          By creating an account or using the Service, you agree to these Terms. If you don't agree, don't use the Service.
        </p>
      </LegalSection>

      <LegalSection title="2. Eligibility">
        <p>
          You must be at least 18 years old and have the legal capacity to enter into a contract. If you're
          registering on behalf of an organization, you confirm you have authority to bind that organization.
        </p>
      </LegalSection>

      <LegalSection title="3. Account and access">
        <ul className="list-disc pl-6 space-y-2">
          <li>You're responsible for keeping your password secure. Report any unauthorized access to us immediately.</li>
          <li>One user per account. Sharing credentials across employees is prohibited.</li>
          <li>Employee accounts are created and managed by the organization's admin.</li>
          <li>We may suspend or terminate accounts that violate these Terms.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Acceptable use">
        <p>You agree NOT to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the Service for illegal purposes or to violate any laws</li>
          <li>Attempt to reverse-engineer, decompile, or extract source code (except open-source components under their respective licenses)</li>
          <li>Overload our infrastructure or bypass rate limits</li>
          <li>Submit content that is defamatory, obscene, or infringes on third-party rights</li>
          <li>Use the Service to spy on employees or violate employment laws</li>
          <li>Resell or white-label the Service without a written agreement</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. Pricing and payment">
        <ul className="list-disc pl-6 space-y-2">
          <li>Free tier is available with usage limits.</li>
          <li>Paid plans are billed monthly or annually via Razorpay in INR.</li>
          <li>GST is charged at applicable rates on top of listed prices.</li>
          <li>Prices may change with 30 days' notice; existing subscriptions honored until renewal.</li>
          <li>Failed payments trigger a 7-day grace period before service suspension.</li>
        </ul>
      </LegalSection>

      <LegalSection title="6. Refund policy">
        <p>
          Full refund available within 7 days of your first paid month, no questions asked. After that,
          you can cancel anytime and won't be charged for the next cycle. We do not offer partial refunds
          for mid-cycle cancellations.
        </p>
      </LegalSection>

      <LegalSection title="7. Your content">
        <p>
          You retain all rights to the content you submit (standup reports, tasks, etc.). By using the
          Service, you grant us a limited license to store, process, and display your content solely to
          provide the Service. We do not use your content to train AI models.
        </p>
      </LegalSection>

      <LegalSection title="8. AI-generated content">
        <p>
          Responses generated by our AI assistants (RAG chat, JSON extraction) are based on your data plus
          third-party LLMs (OpenAI). While we strive for accuracy, AI can produce errors or hallucinations.
          Do not rely on AI outputs for critical business decisions without human review.
        </p>
      </LegalSection>

      <LegalSection title="9. Service availability">
        <p>
          We aim for 99% uptime but don't guarantee it on free or standard plans. Enterprise customers get
          SLA-backed uptime guarantees. Scheduled maintenance will be announced at least 24 hours in advance.
        </p>
      </LegalSection>

      <LegalSection title="10. Termination">
        <p>
          You can delete your account anytime from settings. We may terminate accounts that:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Violate these Terms</li>
          <li>Have unpaid invoices past the grace period</li>
          <li>Are inactive for 12+ months on the Free tier</li>
        </ul>
        <p>Upon termination, we delete your data per the retention rules in our Privacy Policy.</p>
      </LegalSection>

      <LegalSection title="11. Warranties and disclaimers">
        <p>
          The Service is provided "as is" without warranties of any kind. We do not warrant that the Service
          will be uninterrupted, error-free, or free of harmful components. Use at your own risk.
        </p>
      </LegalSection>

      <LegalSection title="12. Limitation of liability">
        <p>
          To the maximum extent permitted by law, Codenscious shall not be liable for indirect, incidental,
          consequential, or punitive damages. Our total liability for any claim shall not exceed the amount
          you paid us in the 12 months preceding the claim.
        </p>
      </LegalSection>

      <LegalSection title="13. Indemnification">
        <p>
          You agree to indemnify and hold harmless Codenscious from any claims arising from your use of the
          Service, your content, or your violation of these Terms.
        </p>
      </LegalSection>

      <LegalSection title="14. Governing law">
        <p>
          These Terms are governed by the laws of India. Any disputes shall be resolved in the courts of
          Delhi, India.
        </p>
      </LegalSection>

      <LegalSection title="15. Changes to Terms">
        <p>
          We may update these Terms. Material changes will be notified via email at least 14 days before
          taking effect. Continued use after changes constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection title="16. Contact">
        <p>
          Questions about these Terms:{" "}
          <a href="mailto:legal@codenscious.com" className="text-primary hover:underline">legal@codenscious.com</a>
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
